### ISSUE TITLE
gzip file types '.gz'

### ISSUE THREAD

**Issue by messif** [novemberfiveco/s3-site-cache-optimizer#1]
Please implement the meta data setting for gzipped files to 'key:content-encoding;value: gzip'

**Comment by rubenvdb** [comment]
Can you provide some more information on the specific use case? Do you want all .gz files to have the content-encoding header? 
Please also check the latest develop-version. There's a --gzip option, which automatically gzips all text files and sets the appropriate headers for the browser to interpret the contents of the files.

**Comment by messif** [comment]
Yes I believe s3 requires all .gz to have that content encoding header to be displayed correct via cloud front and compatible browsers. Mainly css/js files are the use case. But I would expect any text file to benefit from it.

And for the —gzip option does that imply -k parameter to keep the original file, or should i specify that?
