### ISSUE TITLE
SVG files get the wrong content type set.

### ISSUE THREAD

**Issue by messif** [novemberfiveco/s3-site-cache-optimizer#2]
SVG files get set with a content type of application/octet-stream. They should be set to image/svg+xml

**Comment by rubenvdb** [comment]
Mime types are guessed by boto (http://boto.readthedocs.org/en/latest/s3_tut.html#storing-data), not by this tool. Moreover, I checked and found that the mime types set by the tool for SVG files are correctly set to image/svg+xml. 
Can you try upgrading boto to the latest version? If the problem still occurs, please provide more information about how to reproduce the issue: python version, boto version, OS, file for which the issue occurs...
